#ifndef ERROR_TYPES_H
#define ERROR_TYPES_H

typedef enum
{
	SUCCESS,
	BUFFER_NOT_LONG_ENOUGH,
	INDEX_OUT_OF_RANGE,
	MEMORY_NOT_ALLOCATED,
	ELEMENT_UNITIALIZED,
	MEMORY_ALLOCATION_FAILED,
	LIST_EMPTY

}error_status_t;

#endif